"""Evaluate the saved model and write reports/<lang>/eval.json + EVALUATION.md.

    python scripts/evaluate.py [--lang en] [--no-cv]
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from scam_triage.dataset import DATA_DIR, ROOT, load_split, read_jsonl
from scam_triage.evaluate import evaluate_split, grouped_cv, val_thresholds
from scam_triage.model import TriageModel


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--lang", default="en")
    ap.add_argument("--no-cv", action="store_true")
    args = ap.parse_args()

    model = TriageModel.load(lang=args.lang)
    val, test = load_split("val", args.lang), load_split("test", args.lang)
    thresholds = val_thresholds(model, val)
    report = {
        "model": model.meta,
        "thresholds_from_val": thresholds,
        "test": evaluate_split(model, test, thresholds),
    }
    challenge_path = DATA_DIR / args.lang / "challenge.jsonl"
    if challenge_path.exists():
        report["challenge"] = evaluate_split(model, read_jsonl(challenge_path), thresholds)
    if not args.no_cv:
        rows = load_split("train", args.lang) + val + test
        report["grouped_cv"] = grouped_cv(rows, args.lang, C=model.risk_clf.C, type_C=model.type_clf.C)

    out_dir = ROOT / "reports" / args.lang
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "eval.json").write_text(json.dumps(report, indent=2, ensure_ascii=False))
    (out_dir / "EVALUATION.md").write_text(render_markdown(report, args.lang))
    print(f"wrote {out_dir}/eval.json and EVALUATION.md")
    print(summary_line("test", report["test"]))
    if "challenge" in report:
        print(summary_line("challenge", report["challenge"]))


def summary_line(name: str, rep: dict) -> str:
    b, ops = rep["binary"], rep["binary"]["operating_points"]
    return (f"{name}: ROC-AUC={b.get('roc_auc')} PR-AUC={b.get('pr_auc')} "
            f"| high: recall={ops['model_high']['recall']} fpr={ops['model_high']['fpr']} "
            f"| medium: recall={ops['model_medium']['recall']} fpr={ops['model_medium']['fpr']} "
            f"| type macro-F1={rep['type'].get('macro_f1')}")


def _fmt(v) -> str:
    if v is None:
        return "n/a"
    return f"{v:.1%}" if isinstance(v, float) else str(v)


def ops_table(rep: dict) -> str:
    lines = [
        "| Operating point | Threshold | Recall | FPR | FP / legit | Precision (this set) | Precision @1% prev. | @10% | @50% |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    n_legit = rep["binary"]["n_legit"]
    for name, op in rep["binary"]["operating_points"].items():
        pp = op["precision_at_prevalence"]
        lines.append(
            f"| {name} | {op['threshold']:.4f} | {_fmt(op['recall'])} | {op['fpr']:.2%} | {op['fp']} / {n_legit} | "
            f"{_fmt(op['precision'])} | {_fmt(pp['0.01'])} | {_fmt(pp['0.1'])} | {_fmt(pp['0.5'])} |"
        )
    return "\n".join(lines)


def type_table(rep: dict) -> str:
    t = rep["type"]
    if not t:
        return "_No typed scams in this set._"
    lines = [f"Accuracy **{_fmt(t['accuracy'])}**, macro-F1 **{_fmt(t['macro_f1'])}** on {t['n']} scams.", "",
             "| Scam type | F1 |", "|---|---|"]
    lines += [f"| {k} | {_fmt(v)} |" for k, v in t["per_class_f1"].items()]
    return "\n".join(lines)


def error_list(items: list[dict], limit: int = 10) -> str:
    if not items:
        return "_None._"
    return "\n".join(f"- `{it['score']:.3f}` [{it['label']} -> {it['pred_type']}] {it['text']}" for it in items[:limit])


def section(title: str, rep: dict, note: str) -> str:
    b = rep["binary"]
    return f"""## {title}

{note}

n = {b['n']} ({b['n_scam']} scam / {b['n_legit']} legit) · ROC-AUC **{b.get('roc_auc')}** · PR-AUC **{b.get('pr_auc')}**

{ops_table(rep)}

False-positive rate at the model's *high* threshold, by source of legit messages: {", ".join(f"{k} {v:.2%}" for k, v in rep["fpr_by_source_at_high"].items())}

### Scam type

{type_table(rep)}

### Missed scams (score below *medium*)

{error_list(rep["errors"]["missed_scams"])}

### False alarms (legit scored *medium* or above)

{error_list(rep["errors"]["false_alarms"])}

### Correctly flagged, wrong type

{error_list(rep["errors"]["wrong_type"])}
"""


def render_markdown(report: dict, lang: str) -> str:
    m = report["model"]
    parts = [f"""# Evaluation: {lang.upper()} triage model v{m['version']}

_Generated by `scripts/evaluate.py` on {m['trained_at'][:10]}._ Trained on {m['n_train']} messages ({", ".join(m['sources'])}).

**How to read this.** Thresholds are chosen on the validation split at a target false-positive rate (FPR) and then
applied unchanged to each evaluation set, so the FPR column is what a deployment would see, not a tuned number.
`model_high` / `model_medium` are the thresholds the bot uses for its *high* / *medium* risk levels (1% / 5% val FPR).
Precision is shown on the evaluation set as-is and re-weighted to assumed scam prevalences, since the share of scams
among messages people forward to a checker is unknown.
"""]
    parts.append(section("Held-out test set (unseen templates + real UCI ham)", report["test"],
                         "Synthetic messages from templates never seen in training, plus a random 15% of UCI SMS ham."))
    if "challenge" in report:
        parts.append(section("Hand-written challenge set", report["challenge"],
                             "Messages written independently of the generator, modelled on real reported scams and tricky legit texts. "
                             "Small, so each message moves recall by ~2 points; read the examples, not just the numbers."))
    if "grouped_cv" in report:
        cv = report["grouped_cv"]
        rows = "\n".join(f"| {k} | {v['mean']:.3f} ± {v['std']:.3f} |" for k, v in cv.items() if isinstance(v, dict))
        parts.append(f"""## Template-grouped {cv['n_splits']}-fold cross-validation

Each fold holds out whole templates. {cv['note']}.

| Metric | Mean ± std |
|---|---|
{rows}
""")
    parts.append("""## Caveats

- The training data is synthetic. Held-out-template scores measure generalization to new *phrasings* of known scam
  patterns, not to new scam *types*. The challenge set is the better (but small) signal.
- Real legit negatives come from the UCI SMS corpus (UK/Singapore SMS, 2000s), whose style differs from modern
  WhatsApp chat. FPR on today's messages may differ.
- Next: collect consented, labelled forwarded messages from the bot to replace synthetic test data.
""")
    return "\n".join(parts)


if __name__ == "__main__":
    main()
